In diesem Projekt thematisieren wir die Datenanalyse und Visualisierung mit python.

Hauptsächlich konzentrieren wir uns dabei auf die Bibliotheken ~pandas~ und ~matplotlib~.

~pandas~ benutzt man um über tabellenartige Strukturen Daten zu analysieren und zu manipulieren.
~matplotlib~ spielt gut mit ~pandas~ zusammen, diese Bibliothek kann schöne Diagramme aller Art anfertigen.


* Teil 1
Im ersten Teil müssen wir wissen sammeln und einen Überblick der Bibliotheken bekommen.
Ich habe dafür einen Teil von einem Workshop extrahiert, mit dem wir interaktiv lernen können.

Der Workshop wird in einem Jupyter notebook ausgeführt, ein Tool welches häufig für Data Science verwendet wird.
Mit diesen Notebooks kann man code in zellen schreiben, und drum herum schöne Dokumentationen schreiben, und sehr vieles mehr.
Jupyter notebooks kann man sehr einfach mit Anaconda installieren: [[https://www.anaconda.com/distribution/%20][Hier kann man die Software runterladen]].
Nach dem Download müsst ihr einfach den Installer ausführen.

Nach der Installation öffnen wir die Software und starten JupyterLab in der Home-Ansicht. Man wird auf den Browser weitergeleitet.

/Weitere Info's über Jupyter gibt es im Kurs/.

In JupyterLab müsst ihr nun den Code für heute öffnen. Diesen könnt ihr hier herunterladen:  [[https://github.com/falcowinkler/falcowinkler.github.io/raw/master/resources/python-course/python_workshop_pandas_1.zip][*klick*]]
Alle Rechte vorbehalten: © 2015-20178 Alexander C.S. Hendorf, Königsweg GmbH, Mannheim.

Das Original gibt es hier. Falls es mit der Installation nicht klappt, könnt ihr dort das Notebook online ausführen.
https://github.com/alanderex/pydata-pandas-workshop.git
